import type { OrdemServico, Cliente, Tecnico, Dashboard } from "./tipos"

export const clientesMock: Cliente[] = [
  {
    id: "cli-001",
    nome: "Empresa Tech Solutions",
    email: "contato@techsolutions.com",
    telefone: "(11) 3000-0001",
    endereco: "Av. Paulista, 1000 - São Paulo, SP",
    dataRegistro: "2024-01-15",
  },
  {
    id: "cli-002",
    nome: "Indústria Metálica Premium",
    email: "suporte@metalicapremium.com",
    telefone: "(21) 3500-0002",
    endereco: "Rua Industrial, 500 - Rio de Janeiro, RJ",
    dataRegistro: "2024-02-10",
  },
  {
    id: "cli-003",
    nome: "Hospital Central",
    email: "manutencao@hospitalcentral.br",
    telefone: "(85) 2000-0003",
    endereco: "Av. Hospital, 200 - Fortaleza, CE",
    dataRegistro: "2024-03-05",
  },
]

export const tenicosMock: Tecnico[] = [
  {
    id: "tec-001",
    nome: "Carlos Silva",
    email: "carlos.silva@empresa.com",
    telefone: "(11) 99000-0001",
    especialidades: ["Manutenção Preventiva", "Diagnóstico", "Reparos Elétricos"],
    statusDisponibilidade: "disponivel",
  },
  {
    id: "tec-002",
    nome: "Maria Santos",
    email: "maria.santos@empresa.com",
    telefone: "(11) 99000-0002",
    especialidades: ["Instalação", "Configuração", "Suporte Técnico"],
    statusDisponibilidade: "ocupado",
  },
  {
    id: "tec-003",
    nome: "João Oliveira",
    email: "joao.oliveira@empresa.com",
    telefone: "(11) 99000-0003",
    especialidades: ["Manutenção Preventiva", "Reparos Mecânicos"],
    statusDisponibilidade: "disponivel",
  },
  {
    id: "tec-004",
    nome: "Ana Costa",
    email: "ana.costa@empresa.com",
    telefone: "(11) 99000-0004",
    especialidades: ["Diagnóstico", "Reparos Eletrônicos", "Calibração"],
    statusDisponibilidade: "ausente",
  },
]

export const ordensServico: OrdemServico[] = [
  {
    id: "os-001",
    numeroOrdem: "OS-2025-001",
    clienteId: "cli-001",
    tecnicoId: "tec-001",
    equipamentoId: "eq-001",
    tipoServico: "manutencao",
    descricao: "Manutenção preventiva do servidor principal",
    status: "em_progresso",
    prioridade: "alta",
    tarefas: [
      {
        id: "tar-001",
        descricao: "Limpeza de filtros de ar",
        status: "concluida",
        tecnicoAssignado: "tec-001",
        dataFim: "2025-11-04",
      },
      {
        id: "tar-002",
        descricao: "Verificação de componentes internos",
        status: "em_andamento",
        tecnicoAssignado: "tec-001",
        dataInicio: "2025-11-05",
      },
      { id: "tar-003", descricao: "Teste de funcionamento", status: "nao_iniciada" },
    ],
    dataAbertura: "2025-11-03",
    dataVencimento: "2025-11-08",
    notas: "Cliente solicitou atendimento urgente",
    custoEstimado: 500,
    custoReal: 350,
  },
  {
    id: "os-002",
    numeroOrdem: "OS-2025-002",
    clienteId: "cli-002",
    tecnicoId: "tec-002",
    tipoServico: "instalacao",
    descricao: "Instalação de novo sistema de refrigeração",
    status: "pendente",
    prioridade: "critica",
    tarefas: [
      { id: "tar-004", descricao: "Preparação do ambiente", status: "nao_iniciada" },
      { id: "tar-005", descricao: "Instalação do equipamento", status: "nao_iniciada" },
      { id: "tar-006", descricao: "Testes e calibração", status: "nao_iniciada" },
    ],
    dataAbertura: "2025-11-05",
    dataVencimento: "2025-11-06",
    notas: "Instalação agendada para segunda de manhã",
    custoEstimado: 2500,
  },
  {
    id: "os-003",
    numeroOrdem: "OS-2025-003",
    clienteId: "cli-003",
    tecnicoId: "tec-003",
    tipoServico: "reparo",
    descricao: "Reparo de bomba de vácuo defeituosa",
    status: "concluido",
    prioridade: "alta",
    tarefas: [
      { id: "tar-007", descricao: "Diagnóstico da falha", status: "concluida" },
      { id: "tar-008", descricao: "Substituição de peças", status: "concluida" },
      { id: "tar-009", descricao: "Teste de funcionamento", status: "concluida" },
    ],
    dataAbertura: "2025-10-28",
    dataFechamento: "2025-11-02",
    dataVencimento: "2025-11-05",
    notas: "Reparo concluído com sucesso",
    custoEstimado: 800,
    custoReal: 750,
  },
  {
    id: "os-004",
    numeroOrdem: "OS-2025-004",
    clienteId: "cli-001",
    tecnicoId: "tec-001",
    tipoServico: "diagnostico",
    descricao: "Diagnóstico de problema intermitente em impressora",
    status: "em_progresso",
    prioridade: "media",
    tarefas: [
      { id: "tar-010", descricao: "Análise de logs de erro", status: "concluida" },
      { id: "tar-011", descricao: "Testes de conexão", status: "em_andamento" },
    ],
    dataAbertura: "2025-11-04",
    dataVencimento: "2025-11-07",
    notas: "Cliente disponível para testes entre 14h-16h",
    custoEstimado: 300,
  },
  {
    id: "os-005",
    numeroOrdem: "OS-2025-005",
    clienteId: "cli-002",
    tipoServico: "manutencao",
    descricao: "Manutenção de rotina em máquinas industriais",
    status: "pendente",
    prioridade: "baixa",
    tarefas: [
      { id: "tar-012", descricao: "Lubrificação de eixos", status: "nao_iniciada" },
      { id: "tar-013", descricao: "Inspeção de correias", status: "nao_iniciada" },
    ],
    dataAbertura: "2025-11-05",
    dataVencimento: "2025-11-20",
    notas: "Pode ser agendado conforme disponibilidade",
    custoEstimado: 400,
  },
]

export const dashboardMock: Dashboard = {
  totalOrdens: 5,
  ordensAbertos: 2,
  ordensEmProgresso: 2,
  ordensConcluidas: 1,
  taxaConclusao: 20,
  custoDia: 1100,
  tempoMedioAtencimento: 3.5,
}
